Test idempotency for `upgrade-gradle-properties`

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -108,65 +108,64 @@ jobs:
         ./.github/scripts/get-or-create-release-branch.sh output
         cat output > $GITHUB_OUTPUT
 
-#  upgrade-gradle-properties:
-#    name: Upgrade gradle.properties
-#    needs:
-#    - get-or-create-release-branch
-#    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
-#    # we need this here _even though_ the job we depend on is never skipped.
-#    if: |
-#      always() &&
-#      !contains(needs.*.result, 'failure') &&
-#      !contains(needs.*.result, 'cancelled')
-#    runs-on: ubuntu-latest
-#    outputs:
-#      release_branch: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
-#      commit_sha: ${{ steps.gradle-push.outputs.commit_sha }}
-#    steps:
-#    - uses: actions/checkout@v3
-#      with:
-#        ref: ${{ inputs.commit_sha }}
-#        path: smithy-rs
-#        fetch-depth: 0
-#        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
-#    - name: Upgrade gradle.properties
-#      uses: ./smithy-rs/.github/actions/docker-build
-#      with:
-#        action: upgrade-gradle-properties
-#        action-arguments: ${{ inputs.stable_semantic_version }} ${{ inputs.unstable_semantic_version }}
-#    - name: Download all artifacts
-#      uses: ./smithy-rs/.github/actions/download-all-artifacts
-#    - name: Push gradle.properties changes
-#      id: gradle-push
-#      working-directory: upgrade-gradle-properties/smithy-rs
-#      shell: bash
-#      env:
-#        # TODO(GA): specify ${{ inputs.stable_semantic_version }}
-#        SEMANTIC_VERSION: ${{ inputs.unstable_semantic_version }}
-#        RELEASE_COMMIT_SHA: ${{ inputs.commit_sha }}
-#        RELEASE_BRANCH_NAME: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
-#        DRY_RUN: ${{ inputs.dry_run }}
-#      run: |
-#        set -x
-#
-#        # For debugging purposes
-#        git status
-#
-#        if ! git diff-index --quiet HEAD; then
-#          # gradle.properties was changed, we need to commit and push the diff
-#          git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit gradle.properties --message "Upgrade the smithy-rs runtime crates version to ${SEMANTIC_VERSION}"
-#
-#          # This will fail if we tried to release from a non-HEAD commit on the release branch.
-#          # The only scenario where we would try to release a non-HEAD commit from the release branch is
-#          # to retry a release action execution that failed due to a transient issue.
-#          # In that case, we expect the commit to be releasable as-is, i.e. the runtime crate version in gradle.properties
-#          # should already be the expected one.
-#          git push origin "HEAD:refs/heads/${RELEASE_BRANCH_NAME}"
-#
-#          echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
-#        else
-#          echo "commit_sha=${RELEASE_COMMIT_SHA}" > $GITHUB_OUTPUT
-#        fi
+  upgrade-gradle-properties:
+    name: Upgrade gradle.properties
+    needs:
+    - get-or-create-release-branch
+    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
+    # we need this here _even though_ the job we depend on is never skipped.
+    if: |
+      always() &&
+      !contains(needs.*.result, 'failure') &&
+      !contains(needs.*.result, 'cancelled')
+    runs-on: ubuntu-latest
+    outputs:
+      release_branch: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
+      commit_sha: ${{ steps.gradle-push.outputs.commit_sha }}
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        ref: ${{ inputs.commit_sha }}
+        path: smithy-rs
+        fetch-depth: 0
+        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
+    - name: Upgrade gradle.properties
+      uses: ./smithy-rs/.github/actions/docker-build
+      with:
+        action: upgrade-gradle-properties
+        action-arguments: ${{ inputs.stable_semantic_version }} ${{ inputs.unstable_semantic_version }}
+    - name: Download all artifacts
+      uses: ./smithy-rs/.github/actions/download-all-artifacts
+    - name: Push gradle.properties changes
+      id: gradle-push
+      working-directory: upgrade-gradle-properties/smithy-rs
+      shell: bash
+      env:
+        # TODO(GA): specify ${{ inputs.stable_semantic_version }}
+        SEMANTIC_VERSION: ${{ inputs.unstable_semantic_version }}
+        RELEASE_COMMIT_SHA: ${{ inputs.commit_sha }}
+        RELEASE_BRANCH_NAME: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
+      run: |
+        set -x
+
+        # For debugging purposes
+        git status
+
+        if ! git diff-index --quiet HEAD; then
+          # gradle.properties was changed, we need to commit and push the diff
+          git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit gradle.properties --message "Upgrade the smithy-rs runtime crates version to ${SEMANTIC_VERSION}"
+
+          # This will fail if we tried to release from a non-HEAD commit on the release branch.
+          # The only scenario where we would try to release a non-HEAD commit from the release branch is
+          # to retry a release action execution that failed due to a transient issue.
+          # In that case, we expect the commit to be releasable as-is, i.e. the runtime crate version in gradle.properties
+          # should already be the expected one.
+          echo "Would execute: git push origin \"HEAD:refs/heads/${RELEASE_BRANCH_NAME}\""
+
+          echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
+        else
+          echo "commit_sha=${RELEASE_COMMIT_SHA}" > $GITHUB_OUTPUT
+        fi
 #
 #  release:
 #    name: Release
