Update release.yml so we can just test `get-or-create-release-branch`

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -108,176 +108,177 @@ jobs:
         ./.github/scripts/get-or-create-release-branch.sh output
         cat output > $GITHUB_OUTPUT
 
-  upgrade-gradle-properties:
-    name: Upgrade gradle.properties
-    needs:
-    - get-or-create-release-branch
-    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
-    # we need this here _even though_ the job we depend on is never skipped.
-    if: |
-      always() &&
-      !contains(needs.*.result, 'failure') &&
-      !contains(needs.*.result, 'cancelled')
-    runs-on: ubuntu-latest
-    outputs:
-      release_branch: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
-      commit_sha: ${{ steps.gradle-push.outputs.commit_sha }}
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        ref: ${{ inputs.commit_sha }}
-        path: smithy-rs
-        fetch-depth: 0
-        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
-    - name: Upgrade gradle.properties
-      uses: ./smithy-rs/.github/actions/docker-build
-      with:
-        action: upgrade-gradle-properties
-        action-arguments: ${{ inputs.stable_semantic_version }} ${{ inputs.unstable_semantic_version }}
-    - name: Download all artifacts
-      uses: ./smithy-rs/.github/actions/download-all-artifacts
-    - name: Push gradle.properties changes
-      id: gradle-push
-      working-directory: upgrade-gradle-properties/smithy-rs
-      shell: bash
-      env:
-        # TODO(GA): specify ${{ inputs.stable_semantic_version }}
-        SEMANTIC_VERSION: ${{ inputs.unstable_semantic_version }}
-        RELEASE_COMMIT_SHA: ${{ inputs.commit_sha }}
-        RELEASE_BRANCH_NAME: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
-        DRY_RUN: ${{ inputs.dry_run }}
-      run: |
-        set -x
-
-        # For debugging purposes
-        git status
-
-        if ! git diff-index --quiet HEAD; then
-          # gradle.properties was changed, we need to commit and push the diff
-          git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit gradle.properties --message "Upgrade the smithy-rs runtime crates version to ${SEMANTIC_VERSION}"
-
-          # This will fail if we tried to release from a non-HEAD commit on the release branch.
-          # The only scenario where we would try to release a non-HEAD commit from the release branch is
-          # to retry a release action execution that failed due to a transient issue.
-          # In that case, we expect the commit to be releasable as-is, i.e. the runtime crate version in gradle.properties
-          # should already be the expected one.
-          git push origin "HEAD:refs/heads/${RELEASE_BRANCH_NAME}"
-
-          echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
-        else
-          echo "commit_sha=${RELEASE_COMMIT_SHA}" > $GITHUB_OUTPUT
-        fi
-
-  release:
-    name: Release
-    needs:
-    - upgrade-gradle-properties
-    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
-    # we need this here _even though_ the job we depend on is never skipped.
-    if: |
-      always() &&
-      !contains(needs.*.result, 'failure') &&
-      !contains(needs.*.result, 'cancelled')
-    runs-on: ubuntu-latest
-    steps:
-    - name: Install Rust
-      uses: dtolnay/rust-toolchain@master
-      with:
-        toolchain: ${{ env.rust_version }}
-    - name: Checkout smithy-rs
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ needs.upgrade-gradle-properties.outputs.commit_sha }}
-        path: smithy-rs
-        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
-    - name: Generate release artifacts
-      uses: ./smithy-rs/.github/actions/docker-build
-      with:
-        action: generate-smithy-rs-release
-    - name: Download all artifacts
-      uses: ./smithy-rs/.github/actions/download-all-artifacts
-    - name: Push smithy-rs changes
-      shell: bash
-      working-directory: smithy-rs-release/smithy-rs
-      id: push-changelog
-      env:
-        RELEASE_BRANCH_NAME: ${{ needs.upgrade-gradle-properties.outputs.release_branch }}
-      run: |
-        if ! git diff-index --quiet HEAD; then
-          echo "Pushing release commits..."
-          # This will fail if we tried to release from a non-HEAD commit on the release branch.
-          # The only scenario where we would try to release a non-HEAD commit from the release branch is
-          # to retry a release action execution that failed due to a transient issue.
-          # In that case, we expect the commit to be releasable as-is, i.e. the changelog should have already
-          # been processed.
-          git push origin "HEAD:refs/heads/${RELEASE_BRANCH_NAME}"
-        fi
-        echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
-    - name: Tag release
-      uses: actions/github-script@v6
-      with:
-        github-token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
-        script: |
-          const createReleaseScript = require("./smithy-rs/.github/workflows/release-scripts/create-release.js");
-          await createReleaseScript({
-            github,
-            isDryRun: ${{ inputs.dry_run }},
-            releaseManifestPath: "smithy-rs-release/smithy-rs-release-manifest.json",
-            releaseCommitish: "${{ steps.push-changelog.outputs.commit_sha }}"
-          });
-    - name: Publish to crates.io
-      shell: bash
-      working-directory: smithy-rs-release/crates-to-publish
-      env:
-        RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN }}
-      run: |
-        cargo login -- "${RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN}"
-        cargo install --path "$(realpath ../smithy-rs/tools/ci-build/publisher)"
-        # Verify the publisher tool installed successfully
-        publisher --version
-
-        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
-          if [[ ! -f aws-smithy-types/Cargo.toml ]]; then
-            echo "Crates to publish not found!"
-            exit 1
-          fi
-          echo "Checking cargo auth token..."
-          # This version has already been yanked. This command succeeds if we have a token with permission to yank the crate.
-          cargo yank aws-sigv4 --version 0.55.0
-        else
-          publisher publish -y --location .
-        fi
-
-  trim-changelog-next-on-main:
-    name: Remove released entries from CHANGELOG.next.toml on the main branch
-    if: inputs.dry_run == false && needs.get-or-create-release-branch.outputs.new_release_series == true
-    needs:
-    - get-or-create-release-branch
-    - release
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout smithy-rs
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ inputs.commit_sha }}
-        path: smithy-rs
-        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
-    - name: Empty CHANGELOG.next.toml
-      uses: ./smithy-rs/.github/actions/docker-build
-      with:
-        action: generate-new-changelog-next-toml
-    - name: Download all artifacts
-      uses: ./smithy-rs/.github/actions/download-all-artifacts
-    - name: Push smithy-rs changes
-      working-directory: generate-new-changelog-next-toml/smithy-rs
-      shell: bash
-      run: |
-        set -eux
-
-        # This will fail if other commits have been pushed to `main` after `commit_sha`
-        # In particular, this will ALWAYS fail if you are creating a new release series from
-        # a commit that is not the current tip of `main`.
-        # We can build more refined automation to handle this case in the future - until then, it'll require
-        # a manual PR to edit the current CHANGELOG.next.toml file and remove the released entries.
-        git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit CHANGELOG.next.toml --message "Remove released entries from \`CHANGELOG.next.toml\`"
-        git push origin main
+#  upgrade-gradle-properties:
+#    name: Upgrade gradle.properties
+#    needs:
+#    - get-or-create-release-branch
+#    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
+#    # we need this here _even though_ the job we depend on is never skipped.
+#    if: |
+#      always() &&
+#      !contains(needs.*.result, 'failure') &&
+#      !contains(needs.*.result, 'cancelled')
+#    runs-on: ubuntu-latest
+#    outputs:
+#      release_branch: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
+#      commit_sha: ${{ steps.gradle-push.outputs.commit_sha }}
+#    steps:
+#    - uses: actions/checkout@v3
+#      with:
+#        ref: ${{ inputs.commit_sha }}
+#        path: smithy-rs
+#        fetch-depth: 0
+#        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
+#    - name: Upgrade gradle.properties
+#      uses: ./smithy-rs/.github/actions/docker-build
+#      with:
+#        action: upgrade-gradle-properties
+#        action-arguments: ${{ inputs.stable_semantic_version }} ${{ inputs.unstable_semantic_version }}
+#    - name: Download all artifacts
+#      uses: ./smithy-rs/.github/actions/download-all-artifacts
+#    - name: Push gradle.properties changes
+#      id: gradle-push
+#      working-directory: upgrade-gradle-properties/smithy-rs
+#      shell: bash
+#      env:
+#        # TODO(GA): specify ${{ inputs.stable_semantic_version }}
+#        SEMANTIC_VERSION: ${{ inputs.unstable_semantic_version }}
+#        RELEASE_COMMIT_SHA: ${{ inputs.commit_sha }}
+#        RELEASE_BRANCH_NAME: ${{ needs.get-or-create-release-branch.outputs.release_branch }}
+#        DRY_RUN: ${{ inputs.dry_run }}
+#      run: |
+#        set -x
+#
+#        # For debugging purposes
+#        git status
+#
+#        if ! git diff-index --quiet HEAD; then
+#          # gradle.properties was changed, we need to commit and push the diff
+#          git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit gradle.properties --message "Upgrade the smithy-rs runtime crates version to ${SEMANTIC_VERSION}"
+#
+#          # This will fail if we tried to release from a non-HEAD commit on the release branch.
+#          # The only scenario where we would try to release a non-HEAD commit from the release branch is
+#          # to retry a release action execution that failed due to a transient issue.
+#          # In that case, we expect the commit to be releasable as-is, i.e. the runtime crate version in gradle.properties
+#          # should already be the expected one.
+#          git push origin "HEAD:refs/heads/${RELEASE_BRANCH_NAME}"
+#
+#          echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
+#        else
+#          echo "commit_sha=${RELEASE_COMMIT_SHA}" > $GITHUB_OUTPUT
+#        fi
+#
+#  release:
+#    name: Release
+#    needs:
+#    - upgrade-gradle-properties
+#    # See https://github.com/actions/runner/issues/2205#issuecomment-1381988186 for an explanation as to why
+#    # we need this here _even though_ the job we depend on is never skipped.
+#    if: |
+#      always() &&
+#      !contains(needs.*.result, 'failure') &&
+#      !contains(needs.*.result, 'cancelled')
+#    runs-on: ubuntu-latest
+#    steps:
+#    - name: Install Rust
+#      uses: dtolnay/rust-toolchain@master
+#      with:
+#        toolchain: ${{ env.rust_version }}
+#    - name: Checkout smithy-rs
+#      uses: actions/checkout@v3
+#      with:
+#        ref: ${{ needs.upgrade-gradle-properties.outputs.commit_sha }}
+#        path: smithy-rs
+#        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
+#    - name: Generate release artifacts
+#      uses: ./smithy-rs/.github/actions/docker-build
+#      with:
+#        action: generate-smithy-rs-release
+#    - name: Download all artifacts
+#      uses: ./smithy-rs/.github/actions/download-all-artifacts
+#    - name: Push smithy-rs changes
+#      shell: bash
+#      working-directory: smithy-rs-release/smithy-rs
+#      id: push-changelog
+#      env:
+#        RELEASE_BRANCH_NAME: ${{ needs.upgrade-gradle-properties.outputs.release_branch }}
+#      run: |
+#        if ! git diff-index --quiet HEAD; then
+#          echo "Pushing release commits..."
+#          # This will fail if we tried to release from a non-HEAD commit on the release branch.
+#          # The only scenario where we would try to release a non-HEAD commit from the release branch is
+#          # to retry a release action execution that failed due to a transient issue.
+#          # In that case, we expect the commit to be releasable as-is, i.e. the changelog should have already
+#          # been processed.
+#          git push origin "HEAD:refs/heads/${RELEASE_BRANCH_NAME}"
+#        fi
+#        echo "commit_sha=$(git rev-parse HEAD)" > $GITHUB_OUTPUT
+#    - name: Tag release
+#      uses: actions/github-script@v6
+#      with:
+#        github-token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
+#        script: |
+#          const createReleaseScript = require("./smithy-rs/.github/workflows/release-scripts/create-release.js");
+#          await createReleaseScript({
+#            github,
+#            isDryRun: ${{ inputs.dry_run }},
+#            releaseManifestPath: "smithy-rs-release/smithy-rs-release-manifest.json",
+#            releaseCommitish: "${{ steps.push-changelog.outputs.commit_sha }}"
+#          });
+#    - name: Publish to crates.io
+#      shell: bash
+#      working-directory: smithy-rs-release/crates-to-publish
+#      env:
+#        RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN }}
+#      run: |
+#        cargo login -- "${RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN}"
+#        cargo install --path "$(realpath ../smithy-rs/tools/ci-build/publisher)"
+#        # Verify the publisher tool installed successfully
+#        publisher --version
+#
+#        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
+#          if [[ ! -f aws-smithy-types/Cargo.toml ]]; then
+#            echo "Crates to publish not found!"
+#            exit 1
+#          fi
+#          echo "Checking cargo auth token..."
+#          # This version has already been yanked. This command succeeds if we have a token with permission to yank the crate.
+#          cargo yank aws-sigv4 --version 0.55.0
+#        else
+#          publisher publish -y --location .
+#        fi
+#
+#  trim-changelog-next-on-main:
+#    name: Remove released entries from CHANGELOG.next.toml on the main branch
+#    if: inputs.dry_run == false && needs.get-or-create-release-branch.outputs.new_release_series == true
+#    needs:
+#    - get-or-create-release-branch
+#    - release
+#    runs-on: ubuntu-latest
+#    steps:
+#    - name: Checkout smithy-rs
+#      uses: actions/checkout@v3
+#      with:
+#        ref: ${{ inputs.commit_sha }}
+#        path: smithy-rs
+#        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
+#    - name: Empty CHANGELOG.next.toml
+#      uses: ./smithy-rs/.github/actions/docker-build
+#      with:
+#        action: generate-new-changelog-next-toml
+#    - name: Download all artifacts
+#      uses: ./smithy-rs/.github/actions/download-all-artifacts
+#    - name: Push smithy-rs changes
+#      working-directory: generate-new-changelog-next-toml/smithy-rs
+#      shell: bash
+#      run: |
+#        set -eux
+#
+#        # This will fail if other commits have been pushed to `main` after `commit_sha`
+#        # In particular, this will ALWAYS fail if you are creating a new release series from
+#        # a commit that is not the current tip of `main`.
+#        # We can build more refined automation to handle this case in the future - until then, it'll require
+#        # a manual PR to edit the current CHANGELOG.next.toml file and remove the released entries.
+#        git -c 'user.name=AWS SDK Rust Bot' -c 'user.email=aws-sdk-rust-primary@amazon.com' commit CHANGELOG.next.toml --message "Remove released entries from \`CHANGELOG.next.toml\`"
+#        git push origin main
+#
